name: episodeget
version: 1

libraries:
- name: django
  version: "1.5"

handlers:
- url: /static/
  static_path: static

cron:
- description: update_ani_rss
  url: /updater/get_ani_rss
  schedule: "*/9 * * * *"
- description: update_epi_rss
  url: /updater/get_epi_rss
  schedule: "*/7 * * * *"
- description: update_ani_new
  url: /updater/get_ani_new
  schedule: "*/20 * * * *"
- description: update_epi_new
  url: /updater/get_epi_new
  schedule: "*/20 * * * *"

